version: '3.8'

services:
  # MCP HTTP Bridge - runs with Docker socket access
  mcp-bridge:
    build:
      context: .
      dockerfile: Dockerfile.mcp-bridge
    ports:
      - "3001:3001"
    volumes:
      # Mount Docker socket for MCP tools access
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
    networks:
      - chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Visual Chatbot - connects to MCP bridge via HTTP
  visual-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      mcp-bridge:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MCP_BRIDGE_URL=http://mcp-bridge:3001
      - PORT=3003
    networks:
      - chatbot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  chatbot-network:
    driver: bridge
    name: visual-chatbot-network

# Optional: Add volumes for persistent data
volumes:
  mcp-data:
    driver: local